export enum Queue {
  STANDARD = "STANDARD",
  CRITICAL = "CRITICAL",
  EXTERNAL = "EXTERNAL",
  RETRY5SEC = "RETRY5SEC",
  RETRY60SEC = "RETRY60SEC",
  RETRY300SEC = "RETRY300SEC",
  RETRY1500SEC = "RETRY1500SEC",
}
